/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.05/bin/python3: can't open file './python_sequential.py': [Errno 2] No such file or directory
srun: error: ravc4082: task 0: Exited with exit code 2
srun: Terminating StepId=20282623.0
